version: 2
jobs:
  build:
    environment:
        CC_TEST_REPORTER_ID: ${CODE_CLIMATE_TOKEN}
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Style
          command: npm run lint
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build      
      - run:
          name: Test
          command: npm run test-with-coverage
      - run: ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
      - run: ./cc-test-reporter upload-coverage -r ${CODE_CLIMATE_TOKEN}
      - deploy:
          name: Deploy on Expo
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sudo npm install -g exp
              exp login -u ${EXP_EMAIL} -p ${EXP_PASSWORD}
              exp publish
            fi
